model:
  name: yolox-x
  type: dnn
  
  backbone:
    name: darknet
    depth: 1.00
    width: 1.00
    input_dim: 3
    out_features: [dark3, dark4, dark5] #choose darknet outputs 'stem', 'dark 2 ~ 5'
    depthwise: false
    act: "silu"
  
  neck:
    name: pafpn
    depth: ${..backbone.depth}
    in_stages: [dark3, dark4, dark5]
    in_channels: ???
    depthwise: false
    act: silu


  head:
    name: yolox
    num_classes: 3 # waymo open dataset
    strides: ???
    in_channels: ???
    act: silu
    depthwise: false

  postprocess:
    conf_thre: 0.1
    nms_thre: 0.45
