dataset:
  name: waymo
  data_dir: ${oc.env:PROJECT_ROOT, .}/datasets/processed_waymo/
  
  augmentation:
      prob_hflip: 0.5
      rotate:
        prob: 0.8
        min_angle_deg: -6
        max_angle_deg: 6
      zoom:
        prob: 0.8
        zoom_in:
          weight: 8
          factor:
            min: 1.0
            max: 1.5
        zoom_out:
          weight: 2
          factor:
            min: 1
            max: 1.2
